### ISSUE TITLE
Access display should be W1C and not rw, woclr 

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/PeakRDL-html#22]
In the generated html document, the access type must be W1C

![w1c_type_issue](https://user-images.githubusercontent.com/15922511/84596946-40882d00-ae7e-11ea-8dd1-211617581486.jpg)

**Comment by amykyta3** [comment]
The "W1C" designation is specific to UVM. This HTML exporter uses SystemRDL semantics to describe software access properties. From the SystmRDL specification:
![image](https://user-images.githubusercontent.com/12021539/84604817-97294300-ae4d-11ea-968f-031f83b7cb2f.png)

**Comment by muneebullashariff** [comment]
If you see any register documents for projects, the field access doesn't have systemrdl values.
The values should be RW, RO, RW1C, RW1S etc.,

See the below for the reference:
![reg_example](https://user-images.githubusercontent.com/15922511/84628458-4cb7cd00-af06-11ea-8eb1-cd5d3bab15e5.jpg)

This will help in creating the html document aligned with the industry needs/usage.

**Comment by amykyta3** [comment]
As stated before, the "RW, RO, RW1C, RW1S" acronyms are derived from the UVM standard and i'm not interested in converting from one shorthand standard to another shorthand standard.

That said, i can see how to the layman "woclr" would be confusing. Would it be better to have an option for a verbose access mode that displays these in a human-readable format such as "Write-1 to clear"?

**Comment by muneebullashariff** [comment]
> That said, i can see how to the layman "woclr" would be confusing. Would it be better to have an option for a verbose access mode that displays these in a human-readable format such as "Write-1 to clear"?

This would be too verbose and not required in the compact HTML document.

The UVM has values like W1C, W1S etc., but I am suggesting those values in the HTML document.

The values which are used across the industry **for the register document(s)** are as follows:
RW, RO, WO, RW1C, RW1S etc.,

This will make the reader to understand the access type for the register fields when compared to SystemRDL language-specific terms like woclr etc.,

**Comment by wailashi** [comment]
> Would it be better to have an option for a verbose access mode that displays these in a human-readable format such as "Write-1 to clear"?

A logical place for a human-readable format would be in a tooltip. In the following image the cursor is hovering over the text "rclr".
![image](https://user-images.githubusercontent.com/1334557/119303730-e8050680-bc6e-11eb-8a95-a17c97fbc1f5.png)

**Comment by amykyta3** [comment]
Good idea @wailashi. Implemented.
