### ISSUE TITLE
Support for Generation of Word document

### ISSUE THREAD

**Issue by muneebullashariff** [SystemRDL/PeakRDL-html#23]
Is it possible to generate the document in word format? Maybe a feature request.

**Comment by amykyta3** [comment]
I have considered doing a dedicated DOC or PDF exporter but have not had the time to implement. I will consider doing this some day.

Since this would be a separate project and not part of the HTML tool, I'm closing this ticket.

**Comment by muneebullashariff** [comment]
Hi,

I have worked on the project to generate the pdf output, with internal hyperlinks, from the systemRdl input file(s)  

Please do take a look at the below repo:
https://github.com/muneebullashariff/PeakRDL-pdf

I hope this is helpful

**Comment by muneebullashariff** [comment]
[atxmega_spi.pdf](https://github.com/SystemRDL/PeakRDL-html/files/4874826/atxmega_spi.pdf)

**Comment by amykyta3** [comment]
This is awesome!
