### ISSUE TITLE
error: Function is missing a type annotation

### ISSUE THREAD

**Issue by Mohsannaeem** [SystemRDL/PeakRDL-html#25]
Hy I am trying to run.sh script   and installed mypy version "0.761"
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:4: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:33: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:37: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:41: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:45: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:50: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:57: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:62: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:66: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/stringify.py:70: error: Function is missing a type annotation
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/exporter.py:87: error: Argument 1 to "FileSystemLoader" has incompatible type "Dict[str, Any]"; expected "Union[str, _PathLike[Any], Sequence[Union[str, _PathLike[Any]]]]"
/home/dreambig/SystemRDL/PeakRDL-html/peakrdl/html/exporter.py:208: error: Incompatible types in assignment (expression has type "List[Dict[str, Any]]", target has type "Union[BigInt, List[int], int, None]")

What Could be possible issue and solution ? 
Thanks and Regards 
Mohsan

**Comment by amykyta3** [comment]
mypy type checking was something that I started doing only somewhat recently. I hadn't gotten around to adding type annotations everywhere.
Latest commit fixes it.
