### ISSUE TITLE
msb0 fields do not work correctly

### ISSUE THREAD

**Issue by krcb197** [SystemRDL/PeakRDL-html#28]
[SystemRDL 2.0](https://www.accellera.org/images/downloads/standards/systemrdl/SystemRDL_2.0_Jan2018.pdf) allows fields to be defined as:

- `lsb0` (default mode) where the least significant bit (lsb) field is in the lowest bit position (closest to zero)
- `msb0` where the most significant bit (msb) is in the highest bit position (closest to` regwidth-1`)

The following systemRDL code shows both cases:
```
addrmap msb0_and_lsb0 {

    reg {

        default sw = rw;
        default hw = r;
        desc = "register with field defined msb0";
        field {} field_msb_low[0:31];
    } reg_a;

    reg {

        default sw = rw;
        default hw = r;
        desc = "register with field defined lsb0";
        field {} field_lsb_low[31:0];
    } reg_b;

};
```

When the code is generated `reg_a` does not generate correctly, see 
![image](https://user-images.githubusercontent.com/34693973/130319620-72eddade-7700-48cd-bc86-46440cbbb808.png)

**Comment by amykyta3** [comment]
Fixed in v2.1.2
