### ISSUE TITLE
accesstype not support wot and others

### ISSUE THREAD

**Issue by Johnmc104** [SystemRDL/PeakRDL-html#32]
first，thanks for your job
when try
`
hw = rw; wot;
`

return:
`
error:extraneous input 'wot' expect {'}'
`

 i find only "rclr, rset, woset, woclr" can elaborate successful. wot is not supported. would add support for other types？

**Comment by amykyta3** [comment]
SystemRDL does not have a `wot` property, but you can do what you want using the `onwrite` property which is more expressive:
```
hw=rw; onwrite = wot;
```

**Comment by Johnmc104** [comment]
thanks.
since i could use 
`
hw = rw; woclr;
`
I thought the others were similar. thanks for your job
