### ISSUE TITLE
Provide user_template_dir argument when calling via peakrdl tool

### ISSUE THREAD

**Issue by mpriestleyidex** [SystemRDL/PeakRDL-html#35]
This exporter's descriptor doesn't provide a command-line argument for `user_template_dir`. I can't see a good reason why not.

It'd probably make sense to provide cl-args for all the string/boolean args of the exporter:
* `user_template_dir`
* `user_static_dir`
* `generate_source_links`
* `footer`
* `skip_not_present`

**Comment by amykyta3** [comment]
My intent for command line args is to expose functionality that may vary wildly per-invocation of the tool.
Arguments like `user_template_dir` and the other rendering customizations are things that would be relatively static, and only be modified on a per-organization basis so I would prefer to keep them out of the command line args. Instead, I would prefer things like templates be something that are defined using a different mechanism that does not bloat the command-line and hurt user experience (For example an environment config file that you define for your organization, or similar). As I am still working out the details of how I want to structure this part of the PeakRDL command line tool, I have not decided how I want to implement this yet. The HTML generator is not the only tool in the toolchain that has this type of situation.

All that said, I agree that some of these other options are appropriate to be added to the command line args. Will evaluate what makes sense and will update.

**Comment by krcb197** [comment]
@amykyta3 I would favour doing both config file and command line args, this is a similar pattern to other complicated tools, for example pylint. 

For example some people may want to use a make file to manage their build configuration in which case having lots of stuff on the command line is not necessarily a problem.

With the user template directory it may be necessary to have different folders for different PeakRDL tools to avoid file name clashes between tools as many of them potentially use Jinja for their implementation.

**Comment by mpriestleyidex** [comment]
@amykyta3 I see your argument, though it's not clutter if one wants to use it!

For anyone reading wanting to achieve the same, I found it convenient to create a custom exporter that wraps the HTML one, and just override the `do_export` method:

```
import argparse
import peakrdl_html
from systemrdl.node import AddrmapNode

template_path = "path/to/html_templates"

class ExporterDescriptor(peakrdl_html.__peakrdl__.Exporter):
    short_desc = "Generate HTML documentation with custom templates"
    long_desc = "Wrapper around the PeakRDL-html exporter, but overriding the templates with XXX's customisations."

    def do_export(self, top_node: AddrmapNode, options: argparse.Namespace) -> None:
        html = peakrdl_html.HTMLExporter(
            show_signals=options.show_signals,
            user_template_dir=template_path,
        )
        html.export(
            top_node,
            options.output,
            title=options.title,
            home_url=options.home_url,
        )
```

Then give that an entry point of `xxx_html`.

This fits with what @amykyta3 says - I'm overriding `user_template_dir` on an organisational basis, rather than per-call.

**Comment by amykyta3** [comment]
@krcb197 - Good comparison to pylint! I like how theres a variety of options for specifying the pylintrc file location: https://docs.pylint.org/run.html#command-line-options
I'll do something like that!

For the org-config idea, the user template directory would be on a per-tool basis to avoid exactly the collision you mention.

**Comment by amykyta3** [comment]
Addressed in latest release.
See the new configuration framework that was added to the PeakRDL command-line tool: https://peakrdl.readthedocs.io/en/latest/configuring.html
I hope you find it a more appropriate mechanism to set these template paths than via command-line.

**Comment by krcb197** [comment]
I have changed peakrdl_python to match the change made to peakrdl_html to that the user templates are configured via the peakrdl.toml
