### ISSUE TITLE
How to embed HTML into Markdown description

### ISSUE THREAD

**Issue by Risto97** [SystemRDL/PeakRDL-html#36]
Hello, I would like to embed an HTML piece of code into the description field.
Here is an example that fails, I tried to escape the special characters in many ways but have failed.
Do you have a proposed approach for this?
Also is there a way to put description field in a separate file?

    addrmap example {
        name = "Example";
        
        desc = "
        <i> Simple Example with HTML <\i>
        ";

        reg {
            name = "Dummy";
            desc = "Dummy";

            field {
                name = "dummy";
                sw = r; hw = w;} dummy = 0;

        } dummy @ 0x00;
     };

**Comment by amykyta3** [comment]
HTML uses forward slashes not backslashes.
Try `</i>`
