### ISSUE TITLE
Allow search results to open in a new tab.

### ISSUE THREAD

**Issue by rampraa** [SystemRDL/PeakRDL-html#37]
This may be a heavy lift based on how search results are populated. The main drawback in the current setup is that once you click on one of the search results, only way to go back to see other search results is to perform a new search. 

One solution is to populate the search results as a list of html links so that it can be opened in a new tab while current search results are still available in the previous tab.

**Comment by amykyta3** [comment]
Oh wow. Good point!
I thought I converted everything to real URLs (actual `<a href..>` tags) but it looks like i missed these in the search results as these are still implemented as `<div>`s.

Yep I can definitely do that, and what you describe is a very reasonable use-case. Adding an actual link element underneath will still keep the regular left-click behavior, but also let you right-click to open a new tab (or middle-click in some browsers). This also helps with accessibility compliance - it is considered bad-practice for clickable webpage elements to not actually use the correct HTML tag.

**Comment by rampraa** [comment]
One more extension to this request is to add search params to address bar. This will allow user to directly share the search results with another user.

**Comment by amykyta3** [comment]
Fixed in latest release

**Comment by rampraa** [comment]
Thanks!
