### ISSUE TITLE
User enum stringify not working

### ISSUE THREAD

**Issue by hughjackson** [SystemRDL/PeakRDL-html#39]
https://github.com/SystemRDL/PeakRDL-html/blob/2592e93e1f50ee423603345e5f8deb7b8a45ed66/src/peakrdl_html/stringify.py#L28

It looks like is_user_enum function takes a type, should the check in stringify call as `rdltypes.is_user_enum(type(value))` instead?

**Comment by hughjackson** [comment]
Also the actual enum stringify function is not working for me, might just want to be str(value)

**Comment by amykyta3** [comment]
Do you have an example of RDL you can share where this fails?

**Comment by hughjackson** [comment]
Sorry about that, it is a bit of a corner case as well :) I found issues when trying to use a custom property with an enum as the type:

```
enum cust_prop_enum { 
    off = 0;
    on  = 1;
};
property cust_prop { type = cust_prop_enum; component = field; };

addrmap test_map {
    reg {
        field {
            cust_prop = cust_prop_enum::on;
        } test_field;
    } test_reg;
};
``` 

Generated with the custom field as an extra doc property

```python
from systemrdl import RDLCompiler, RDLCompileError
from peakrdl_html import HTMLExporter

rdlc = RDLCompiler()
rdlc.compile_file('testcase.rdl', [])
root = rdlc.elaborate()

html = HTMLExporter(extra_doc_properties=['cust_prop'])
html.export(root, '.')
``` 

Which generates a nice big stack trace ending in:

```
  File "/eng/proj/digital_ip/ref/python3.9/site-packages/peakrdl_html/templates/macros.html", line 32, in template
    <td>{{stringify_rdl_value(node.get_property(prop), node)}}</td>
  File "/eng/proj/digital_ip/ref/python3.9/site-packages/peakrdl_html/stringify.py", line 32, in stringify_rdl_value
    raise RuntimeError
```

This code works as I expect with the two suggested updates (although they may not be the complete/correct fix)

**Comment by amykyta3** [comment]
Will be fixed in next release.
Thanks for reporting!
