### ISSUE TITLE
Add more information into addrmap content 

### ISSUE THREAD

**Issue by haimag** [SystemRDL/PeakRDL-html#41]
Current `addrmap.html` only has a table with `Offset/Identifier/Name`,  can add more reg-field information into the table? such as for the file [atxmega_spi.rdl](https://github.com/SystemRDL/systemrdl-compiler/blob/main/examples/atxmega_spi.rdl), add a table like this:

![addrmap](https://github.com/SystemRDL/PeakRDL-html/assets/5843238/3c886bd3-4cbf-424f-a35c-37eb62a1debe)

**Comment by amykyta3** [comment]
Field information is more appropriately displayed by clicking through to the register page.

Displaying field information in the addrmap memory map view would have some pretty significant scaling issues that would make it very cluttered and difficult to read. Consider the very common situation where you have a 32-bit or 64-bit register, and each bit has a named field. This would be impossible to display sensibly in a horizontal field table without having all sorts of text overflow and accessibility issues.
